### ISSUE TITLE
Unable to run `npm install` or build `master` while using other methods to install

### ISSUE THREAD

**Issue by isleshocky77** [trakt-tools/universal-trakt-scrobbler#219]
I'm attempting to build on `master` and running across a couple of issues.

1. `npm install` fails 

```
user@computer[~/Projects/universal-trakt-scrobbler](master)$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: pug-loader@2.4.0
npm ERR! Found: pug@3.0.2
npm ERR! node_modules/pug
npm ERR!   dev pug@"^3.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer pug@"^2.0.0" from pug-loader@2.4.0
npm ERR! node_modules/pug-loader
npm ERR!   dev pug-loader@"^2.4.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: pug@2.0.4
npm ERR! node_modules/pug
npm ERR!   peer pug@"^2.0.0" from pug-loader@2.4.0
npm ERR!   node_modules/pug-loader
npm ERR!     dev pug-loader@"^2.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-11-21T04_42_19_720Z-debug-0.log
```

*NOTE* I tried this on `lts/hydrogen`  and `lts/gallium`

2. I got this to finally install by using `npm install --legacy-peer-deps`; however, I then couldn't get it to build without

```
user@machine[~/Projects/universal-trakt-scrobbler](master)$ npm run build-dev

> universal-trakt-scrobbler@1.0.0 build-dev
> cross-env ENV=development webpack --env development

[webpack-cli] Failed to load '/home/user/Projects/universal-trakt-scrobbler/webpack.config.ts' config
[webpack-cli] webpack.config.ts:210:14 - error TS2322: Type 'TsconfigPathsPlugin' is not assignable to type '"..." | ResolvePluginInstance'.
  Type 'TsconfigPathsPlugin' is not assignable to type 'ResolvePluginInstance'.
    Types of property 'apply' are incompatible.
      Type '(resolver: import("/home/user/Projects/universal-trakt-scrobbler/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void' is not assignable to type '(resolver: import("/home/user/Projects/universal-trakt-scrobbler/node_modules/webpack/types").Resolver) => void'.
        Types of parameters 'resolver' and 'resolver' are incompatible.
          Type 'import("/home/user/Projects/universal-trakt-scrobbler/node_modules/webpack/types").Resolver' is not assignable to type 'import("/home/user/Projects/universal-trakt-scrobbler/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver'.
            The types of 'options.plugins' are incompatible between these types.
              Type 'Plugin[]' is not assignable to type 'Plugin[]'. Two different types with this name exist, but they are unrelated.
                Type 'Plugin' is not assignable to type 'Plugin'. Two different types with this name exist, but they are unrelated.
                  Type '{ apply: (arg0: Resolver) => void; }' is not assignable to type 'Plugin'.
                    Type '{ apply: (arg0: import("/home/user/Projects/universal-trakt-scrobbler/node_modules/webpack/types").Resolver) => void; }' is not assignable to type '{ apply: (arg0: import("/home/user/Projects/universal-trakt-scrobbler/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void; }'.
                      Types of property 'apply' are incompatible.
                        Type '(arg0: import("/home/user/Projects/universal-trakt-scrobbler/node_modules/webpack/types").Resolver) => void' is not assignable to type '(arg0: import("/home/user/Projects/universal-trakt-scrobbler/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver) => void'.
                          Types of parameters 'arg0' and 'arg0' are incompatible.
                            Type 'import("/home/user/Projects/universal-trakt-scrobbler/node_modules/tsconfig-paths-webpack-plugin/lib/plugin.temp.types").Resolver' is not assignable to type 'import("/home/user/Projects/universal-trakt-scrobbler/node_modules/webpack/types").Resolver'.
                              Types of property 'options' are incompatible.
                                Property 'extensionAlias' is missing in type 'ResolveOptions' but required in type 'ResolveOptionsTypes'.

210    plugins: [new plugins.tsConfigPaths()],
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/webpack/types.d.ts:9631:2
    9631  extensionAlias: ExtensionAliasOption[];
          ~~~~~~~~~~~~~~
    'extensionAlias' is declared here.
```

3. So then I looked at your workflows and notice it's using `pnpm`. So I tried using that. I was able to get it to `pnpm install` just fine; however, the build still failed

```
user@machine[~/Projects/universal-trakt-scrobbler](master)$ pnpm build dev

> universal-trakt-scrobbler@1.0.0 build /home/user/Projects/universal-trakt-scrobbler
> cross-env ENV=production webpack --env production "dev"

10% building 0/23 entries 23/23 dependencies 0/23 modulesError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack-sources@3.2.1/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:827:5
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack-sources@3.2.1/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/user/Projects/universal-trakt-scrobbler/node_modules/.pnpm/webpack@5.53.0_webpack-cli@4.8.0/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
 ELIFECYCLE  Command failed with exit code 1.
```

*NOTE* as in the workflow, `pnpm run check` works just fine; however, the workflow doesnt' actually seem to be doing a build.

**Comment by rafaelgomesxyz** [comment]
Yep, the master build started failing as well, with that same error: https://github.com/trakt-tools/universal-trakt-scrobbler/actions/runs/3408744115/jobs/5669874948

I'll investigate, likely an issue with one of the dependencies.

**Comment by MrMamen** [comment]
The documentation should reflect that we use pnpm, or we should try to make this work with npm as well. @rafaelgomesxyz

**Comment by isleshocky77** [comment]
@MrMamen I noted above that I tried to use `pnpm` as well and it's failing with it. Not sure if you were inferring it works with `pnpm` or if you just wanted to use this as a place to document that we should be using `pnpm`.
