### ISSUE TITLE
Prime fails to load history after successful sync

### ISSUE THREAD

**Issue by badelie** [trakt-tools/universal-trakt-scrobbler#234]
When I try to sync Prime history, after scrolling down the loading of history eventually fails with the following error. I cannot figure out if this is related to a specific date in the past, API request limits, or something else.

After this failure, I cannot reload the history page anymore, I just get a Failed to Load error.

**EDIT**: I cannot find if this was reported before, sorry.

```java
[UTS] Failed to load history. Error: {"request":{"url":"https://www.primevideo.com/gp/video/api/getWatchHistorySettingsPage?widgetArgs=%7B%22nextToken%22%3A%22eyJ2ZXJzaW9uIjoiVjEiLCJwYWdpbmF0aW9uSW5mbyI6ImV5SjBhVzFsVTNSaGJYQWlPakUyTnpJME5EYzBPVGt1TVRreE1qSXdNREF3TENKb2IzUlRkRzl5WVdkbFVHRm5hVzVoZEdsdmJsUnZhMlZ1SWpwN0lsQnliMlpwYkdWSlpDSTZleUp6SWpvaVFUZEhXVlZJVFRCWFVqTTBVU0lzSW00aU9tNTFiR3dzSW1JaU9tNTFiR3dzSW0waU9tNTFiR3dzSW13aU9tNTFiR3dzSW5OeklqcHVkV3hzTENKdWN5STZiblZzYkN3aVluTWlPbTUxYkd3c0ltNTFiR3dpT201MWJHd3NJbUp2YjJ3aU9tNTFiR3g5TENKSWFXUmtaVzR0VFc5a2FXWnBaV1JFWVhSbElqcDdJbk1pT2lJd0xUSXdNVGt0TVRJdE1UVlVNakU2TkRZNk1UZ3VNVEl5V2lJc0ltNGlPbTUxYkd3c0ltSWlPbTUxYkd3c0ltMGlPbTUxYkd3c0ltd2lPbTUxYkd3c0luTnpJanB1ZFd4c0xDSnVjeUk2Ym5Wc2JDd2lZbk1pT201MWJHd3NJbTUxYkd3aU9tNTFiR3dzSW1KdmIyd2lPbTUxYkd4OUxDSlFjbTltYVd4bFNXUXRWR2wwYkdWSlpDSTZleUp6SWpvaVFUZEhXVlZJVFRCWFVqTTBVUzFoYlhwdU1TNWtkaTVuZEdrdU1qSmlOelptTUdZdE9UbG1PUzFoT0dZNExUTTNOak10WlRZNFl6Y3dZV1prWXpGbElpd2liaUk2Ym5Wc2JDd2lZaUk2Ym5Wc2JDd2liU0k2Ym5Wc2JDd2liQ0k2Ym5Wc2JDd2ljM01pT201MWJHd3NJbTV6SWpwdWRXeHNMQ0ppY3lJNmJuVnNiQ3dpYm5Wc2JDSTZiblZzYkN3aVltOXZiQ0k2Ym5Wc2JIMTlmUT09In0=%22%7D","method":"GET","withHeaders":{"x-requested-with":"XMLHttpRequest"},"withRateLimit":{"id":"default","maxRPS":{"*":2}}},"status":0,"text":"","isCanceled":false}
    at history.js:2:283393
    at p (history.js:2:265649)
    at Generator.<anonymous> (history.js:2:267004)
    at Generator.throw (history.js:2:266012)
    at e (history.js:2:273845)
    at l (history.js:2:274084)

t.<computed> @ history.js:2
value @ history.js:2
(anonymous) @ history.js:75
p @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
e @ history.js:2
l @ history.js:2
Promise.then (async)
e @ history.js:2
s @ history.js:2
Promise.then (async)
e @ history.js:2
s @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:75
(anonymous) @ history.js:205
p @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
e @ history.js:2
s @ history.js:2
Promise.then (async)
e @ history.js:2
s @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:2
(anonymous) @ history.js:205
r @ history.js:205
value @ history.js:205
value @ history.js:205
r._onItemsRendered @ history.js:205
(anonymous) @ history.js:102
(anonymous) @ history.js:102
d._callPropsCallbacks @ history.js:102
d.componentDidUpdate @ history.js:102
ds @ history.js:2
Rl @ history.js:2
t.unstable_runWithPriority @ history.js:2
$o @ history.js:2
El @ history.js:2
pl @ history.js:2
(anonymous) @ history.js:2
t.unstable_runWithPriority @ history.js:2
$o @ history.js:2
Vo @ history.js:2
qo @ history.js:2
De @ history.js:2
(anonymous) @ history.js:2
Ar @ history.js:2
Jt @ history.js:2
Qt @ history.js:2
t.unstable_runWithPriority @ history.js:2
Xt @ history.js:2
```

**Comment by downey-lv** [comment]
Duplicate #211

**Comment by downey-lv** [comment]
I think this will be quite hard for anyone else to troubleshoot as this exact URL is specific to your account. 
nextToken part of the URL is returned by the Prime API and then used by the extension to load all history (as if you'd have clicked a Load more button). 

Can you try calling the API URL directly to see what is the response that causes the error?

Also, have you tried a clean install of the plugin?

**Comment by DrSeussFreak** [comment]
I just did a clean install of the plugin on a new instance of chrome.  I was able to login the first time to Amazon and sync the history (well, most of it, I stopped and started again later, closing the screen) to trakt, but every time after that I get this error

![Screenshot 2023-06-30 at 11 19 42 AM](https://github.com/trakt-tools/universal-trakt-scrobbler/assets/175500/72ab613b-b8a5-4eb8-86d6-c4535e66da4a)

then it kicks me back to the history screen to choose which service

**Comment by jdrx99** [comment]
I am using amazon prime from india and getting the same issue.

Uncaught (in promise) function t(){try{o||null==r.return||r.return()}finally{if(a)throw t}}

[UTS] Failed to load history. Error: {"request":{"url":"https://www.primevideo.com/region/eu/api/getWatchHistorySettingsPage?widgetArgs=%7B%22nextToken%22%3A%22eyJ2ZXJzaW9uIjoiVjEiLCJwYWdpbmF0aW9uSW5mbyI6ImV5SjBhVzFsVTNSaGJYQWlPakUzTVRBME9ETXdNell1T1RVMk5ETXpNREF3TENKb2IzUlRkRzl5WVdkbFVHRm5hVzVoZEdsdmJsUnZhMlZ1SWpwN0lsQnliMlpwYkdWSlpDSTZleUp6SWpvaVFUSmFPVk5CV0UweU5qbFpWMVFpTENKdUlqcHVkV3hzTENKaUlqcHVkV3hzTENKdElqcHVkV3hzTENKc0lqcHVkV3hzTENKemN5STZiblZzYkN3aWJuTWlPbTUxYkd3c0ltSnpJanB1ZFd4c0xDSnVkV3hzSWpwdWRXeHNMQ0ppYjI5c0lqcHVkV3hzZlN3aVNHbGtaR1Z1TFUxdlpHbG1hV1ZrUkdGMFpTSTZleUp6SWpvaU1DMHlNREl6TFRBNExUSXdWREV3T2pVeE9qVTFMakk1TURFeU9Wb2lMQ0p1SWpwdWRXeHNMQ0ppSWpwdWRXeHNMQ0p0SWpwdWRXeHNMQ0pzSWpwdWRXeHNMQ0p6Y3lJNmJuVnNiQ3dpYm5NaU9tNTFiR3dzSW1KeklqcHVkV3hzTENKdWRXeHNJanB1ZFd4c0xDSmliMjlzSWpwdWRXeHNmU3dpVUhKdlptbHNaVWxrTFZScGRHeGxTV1FpT25zaWN5STZJa0V5V2psVFFWaE5Nalk1V1ZkVUxXRnRlbTR4TG1SMkxtZDBhUzQyTXpRelpqZzRZaTB6TVdRM0xUUmhaR1V0T1RFM1lTMHpNRE5oWVRjd01XVXlNVFlpTENKdUlqcHVkV3hzTENKaUlqcHVkV3hzTENKdElqcHVkV3hzTENKc0lqcHVkV3hzTENKemN5STZiblZzYkN3aWJuTWlPbTUxYkd3c0ltSnpJanB1ZFd4c0xDSnVkV3hzSWpwdWRXeHNMQ0ppYjI5c0lqcHVkV3hzZlgxOSJ9%22%7D","method":"GET","cancelKey":"default","withHeaders":{"x-requested-with":"XMLHttpRequest"},"signal":{}},"status":-1,"isCanceled":false}
Context
history.html#/amazon-prime

**Comment by MrMamen** [comment]
Fixed in #449
