### ISSUE TITLE
trak and history doesent work 

### ISSUE THREAD

**Issue by tomfrontman** [trakt-tools/universal-trakt-scrobbler#406]
### Additional Information

- **OS + Version:**
- **Browser + Version: Arc+ 1.22.1 (54505) / Chromium Engine Version 129.0.6668.90**
- **Country/Region: Italy**

**Comment by RaoulJacobs** [comment]
I have the same problem on latest edge/chromium and firefox and version 0.4 and latest released plugin
with the latest beta release it works again, strange because i tried it before
Thx

**Comment by eugeniosaintemarie** [comment]
Solved https://github.com/trakt-tools/universal-trakt-scrobbler/issues/402#event-14499083754

**Comment by tomfrontman** [comment]
it still doesn't work for me

**Comment by MrMamen** [comment]
In case you don't use the beta-versions, I released a new prod version now.

**Comment by SpiderAang** [comment]
I have the same problem.
**Edge (Browser) Version**: 131.0.2903.112 (Released Version) (64 bit)
**Universal Takt Scrobbler Version**: 0.4.1
Netflix Plarform: Netflix App(It was actualy running from edge Browser) from Microsoft Store/Netflix Site from Edge (Browser) Tab.

**Comment by adri1m64** [comment]
Hello, same case for me:

Here are the log:
```
[UTS] Failed to execute action. e: {"request":{"url":"https://www.netflix.com/api/shakti/mre/viewingactivity?languages=en-US&authURL=blablabla\\x3D\\x3D&pg=0","method":"GET","cancelKey":"default","withHeaders":{},"signal":{}},"status":-1,"isCanceled":false}
    at t.<anonymous> (chrome-extension://mbhadeogepkjdjeikcckdkjdjhhkhlid/background.js:2:117728)
    at d (chrome-extension://mbhadeogepkjdjeikcckdkjdjhhkhlid/background.js:2:91517)
    at Generator.<anonymous> (chrome-extension://mbhadeogepkjdjeikcckdkjdjhhkhlid/background.js:2:92859)
    at Generator.next (chrome-extension://mbhadeogepkjdjeikcckdkjdjhhkhlid/background.js:2:91946)
    at t (chrome-extension://mbhadeogepkjdjeikcckdkjdjhhkhlid/background.js:2:99034)
    at s (chrome-extension://mbhadeogepkjdjeikcckdkjdjhhkhlid/background.js:2:99237)
```

blablabla is a long auth URL and i modified to send here

Tested on both Edge and Fresh Google Chrome
